version: "3.8"

services:
  localhost:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_DB: trading_game
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - backend_network
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: python /app/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    networks:
      - backend_network

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_app worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  redis:
    image: redis:6
    ports:
      - "6379:6379"

networks:
  backend_network:
    driver: bridge

volumes:
  pg_data:
    driver: local
