version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    command: python /code/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_app worker -l info
    volumes:
      - ./backend:/code
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  redis:
    image: redis:6
    ports:
      - "6379:6379"
