# Generated by Django 4.2.20 on 2025-03-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basegame',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
