# Generated by Django 4.2.20 on 2025-03-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='currentPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
