# Generated by Django 4.2.20 on 2025-03-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_player_money_alter_stock_currentprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='basegame',
            name='seed',
            field=models.CharField(default='', max_length=256),
        ),
    ]
