# Generated by Django 4.2.20 on 2025-03-28 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_basegame_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='players',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.IntegerField(choices=[(0, 'Player'), (1, 'Bot')])),
                ('money', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='basegame',
            name='num_players',
            field=models.BigIntegerField(default=1),
        ),
    ]
