# Generated by Django 4.2.20 on 2025-03-28 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_players_basegame_num_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Stock XYZ', max_length=256)),
                ('description', models.TextField(default='Default stock description')),
                ('currentPrice', models.FloatField(default=0)),
                ('buyOrders', models.JSONField()),
                ('sellOrders', models.JSONField()),
            ],
        ),
        migrations.RenameModel(
            old_name='players',
            new_name='Player',
        ),
    ]
