# Generated by Django 4.2.20 on 2025-03-31 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_basegame_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='basegame',
            name='stock',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='app.stock'),
        ),
    ]
