# Generated by Django 4.2.20 on 2025-03-31 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_basegame_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basegame',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='app.stock'),
        ),
    ]
