# Generated by Django 4.2.20 on 2025-03-31 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_basegame_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='buyOrders',
            new_name='buy_orders',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='currentPrice',
            new_name='current_price',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='sellOrders',
            new_name='sell_orders',
        ),
    ]
