# Generated by Django 4.2.20 on 2025-03-31 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_buyorders_stock_buy_orders_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='name',
            new_name='stock_name',
        ),
        migrations.AddField(
            model_name='stock',
            name='company_name',
            field=models.CharField(default='Company XYZ', max_length=256),
        ),
    ]
