# Generated by Django 4.2.20 on 2025-03-31 21:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_name_stock_stock_name_stock_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='industries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='stock',
            name='buy_orders',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sell_orders',
            field=models.JSONField(default={}),
        ),
    ]
