# Generated by Django 4.2.20 on 2025-03-31 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_stock_industries_alter_stock_buy_orders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='buy_orders',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sell_orders',
            field=models.JSONField(default=dict),
        ),
    ]
