# Generated by Django 4.2.20 on 2025-04-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_stock_buy_orders_alter_stock_sell_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='basegame',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basegame',
            name='last_paused',
            field=models.FloatField(default=-1),
        ),
    ]
