# Generated by Django 4.2.20 on 2025-04-05 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_basegame_is_paused_basegame_last_paused'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basegame',
            old_name='last_paused',
            new_name='time_to_next_tick',
        ),
    ]
