# Generated by Django 4.2.20 on 2025-04-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_last_paused_basegame_time_to_next_tick'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='first_tick_index',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='stock',
            name='ticks_generated',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='underlying_stock',
            field=models.CharField(default='', max_length=256),
        ),
    ]
