# Generated by Django 4.2.20 on 2025-04-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_stock_first_tick_index_stock_ticks_generated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basegame',
            name='is_paused',
            field=models.BooleanField(default=True),
        ),
    ]
