# Generated by Django 4.2.20 on 2025-04-07 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_stock_past_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='past_values',
        ),
    ]
