# Generated by Django 4.2.20 on 2025-04-07 23:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_stock_past_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='next_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, default=0, max_digits=20), default=list, size=None),
        ),
        migrations.AddField(
            model_name='stock',
            name='past_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, default=0, max_digits=20), default=list, size=None),
        ),
    ]
