# Generated by Django 4.2.20 on 2025-05-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_stock_next_values_stock_past_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='basegame',
            name='players',
            field=models.ManyToManyField(related_name='players', to='app.player'),
        ),
        migrations.AlterField(
            model_name='basegame',
            name='num_players',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.IntegerField(choices=[(0, 'System'), (1, 'Player'), (2, 'Bot')], default=0),
        ),
    ]
