# Generated by Django 4.2.20 on 2025-05-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_basegame_players_alter_basegame_num_players_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='owned_stocks',
            field=models.JSONField(default=dict),
        ),
    ]
