# Generated by Django 4.2.20 on 2025-05-14 00:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_player_owned_stocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(0, 'Order in Solo Mode')], default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('quantity', models.BigIntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('from_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_player', to='app.player')),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='pending_orders',
            field=models.ManyToManyField(related_name='pending_orders', to='app.order'),
        ),
    ]
