# Generated by Django 4.2.20 on 2025-05-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_order_stock_pending_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Order has been placed'), (1, 'Order has been fulfilled and is pending'), (2, 'Order has been fulfilled and cannot be changed'), (3, 'Order has been cancelled')], default=0),
        ),
    ]
