# Generated by Django 4.2.20 on 2025-05-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='fulfilled_orders',
            field=models.ManyToManyField(related_name='fulfilled_orders', to='app.order'),
        ),
    ]
