# Generated by Django 4.2.20 on 2025-06-17 04:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_stock_fulfilled_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_type', models.IntegerField(choices=[(0, 'Tutorial for the base game'), (1, 'Base game with a single player'), (2, 'Base game where player trades against bots'), (3, 'Tutorial for options mode'), (4, 'Game where player can trade options with bots')], default=1)),
                ('num_bots', models.IntegerField(default=30)),
                ('num_market_makers', models.IntegerField(default=3)),
                ('num_trading_days', models.IntegerField(default=10)),
                ('num_ticks_per_day', models.IntegerField(default=20)),
                ('time_between_ticks', models.FloatField(default=1.5)),
                ('starting_cash', models.IntegerField(default=1000)),
                ('volatility', models.IntegerField(default=10)),
                ('seed', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Order Placed'), (1, 'Order Filled'), (2, 'Order Confirmed'), (3, 'Order Cancelled')], default=0),
        ),
        migrations.AddField(
            model_name='basegame',
            name='settings',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='app.gamesettings'),
        ),
    ]
