# Generated by Django 4.2.23 on 2025-06-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_gamesettings_alter_order_status_basegame_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='day_confirmed_on',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='day_placed_on',
            field=models.IntegerField(default=0),
        ),
    ]
