# Generated by Django 4.2.23 on 2025-06-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_order_day_confirmed_on_order_day_placed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='play_style',
            field=models.IntegerField(default=0),
        ),
    ]
