# Generated by Django 4.2.23 on 2025-06-29 00:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_player_play_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='interest_earned',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, default=0, max_digits=20), default=[], size=None),
        ),
        migrations.AddField(
            model_name='player',
            name='interest_paid',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, default=0, max_digits=20), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='game_type',
            field=models.IntegerField(choices=[(0, 'Base game tutorial'), (1, 'Base game (solo)'), (2, 'Base game (regular)'), (3, 'Options mode tutorial'), (4, 'Options mode')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.IntegerField(choices=[(0, 'Order in Solo Mode'), (1, 'Order in Regular Mode')], default=0),
        ),
    ]
