# Generated by Django 4.2.23 on 2025-06-29 00:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_player_interest_earned_player_interest_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='interest_earned',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, default=0, max_digits=20), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='player',
            name='interest_paid',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, default=0, max_digits=20), default=list, size=None),
        ),
    ]
